name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Ensure Gradle Wrapper is executable
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle Wrapper
        run: ./gradlew build

          # Set up Python to run the script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the specific version of Python you need

      - name: Install dependencies (if any)
        run: pip install requests  # If your script uses any Python packages

      - name: List files in GitHub Actions directory
        run: ls -la .github/scripts

      - name: Ensure script is executable
        run: chmod +x .github/scripts/upload_to_confluence.py

      - name: Upload README to Confluence
        run: python .github/scripts/upload_to_confluence.py
        env:
          CONFLUENCE_PAGE_TITLE: Pipeline-demo-service
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}